name: happy-commit
on:
  - pull_request
permissions:
  contents: read
  pull-requests: write
  issues: write
jobs:
  happy:
    uses: kitsuyui/gh-actions-workflows/.github/workflows/happy-commit.yml@3717c78af3a5e594b7a81b063276e15fac7e08fc
